### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by mtmjr92** [rdbo/ronix#1]
im using Linux mint 20.3 and getting this error can help @rdbo.

![Screenshot from 2022-01-09 12-04-32](https://user-images.githubusercontent.com/19805433/148688199-41f77f66-31d0-482f-b4c5-d5648199bc9b.png)

`user@user-X470-AORUS-ULTRA-GAMING:~/projects-git/ronix$ ./compile.sh 
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/projects-git/ronix/build
[  3%] Building CXX object CMakeFiles/imgui.dir/imgui/backends/imgui_impl_opengl2.cpp.o
[  7%] Building CXX object CMakeFiles/imgui.dir/imgui/backends/imgui_impl_sdl.cpp.o
In file included from /usr/include/c++/9/stdlib.h:36,
                 from /usr/include/SDL2/SDL_stdinc.h:40,
                 from /usr/include/SDL2/SDL_main.h:25,
                 from /usr/include/SDL2/SDL.h:32,
                 from /home/user/projects-git/ronix/imgui/backends/imgui_impl_sdl.cpp:57:
/usr/include/c++/9/cstdlib:41:10: fatal error: bits/c++config.h: No such file or directory
   41 | #include <bits/c++config.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/imgui.dir/build.make:90: CMakeFiles/imgui.dir/imgui/backends/imgui_impl_sdl.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/imgui.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
user@user-X470-AORUS-ULTRA-GAMING:~/projects-git/ronix$ 
`

**Comment by rdbo** [comment]
Counter-Strike Source is a 32 bit application, so the hack needs to be that as well. Install `gcc-multilib` and `g++-multilib` to get the 32 bit libraries.
